name: Build Action
on:
  pull_request:
    branches:
      - main
jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i
  eslint:
    name: run ESlint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run Eslint
        run: npm run lint
  build:
    name: build
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm run build
  analyze:
    name: analyze
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test

      - name: Lighthouse
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun
