name: Build Action
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Run Eslint
        needs: Install dependencies
        run: npm run lint

      - name: Build project
        needs: Install dependencies
        run: npm run build

      - name: Test
        needs: Build project
        run: npm run test

      - name: Lighthouse
        needs: Build project
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun
